spring:
  data:
    mongodb:
      uri: mongodb://localhost/device


config:
  corporateId: 305f55e28c334b958777f9c037a02cd9
  corporatePasswd: 1q2w3e4r
  testSn:
    - 001221A00B39
    - 0011613003C8

#logging:
#  file: ./device_server_log/log.log
