spring:
  data:
    mongodb:
      uri: mongodb://localhost/device
  mvc:
    favicon:
      enabled: false

logging:
  file: ./logs/device_server.log

appCron:
  apiCount: 0 0 * * * *
  dataSync: 0 0 * * * *
  thunderSync: 0 0 1 * * *

config:
  corporateId: 305f55e28c334b958777f9c037a02cd9
  corporatePasswd: 1q2w3e4r
  intervalInMs: 180000
  testSn:
  - '001221A00B39'
  - '0011613003C8'
  - '001221A00BB5'
  - '001221A00B25'
  - '001161300365'
  - '001221A00AF7'
  - '001221A00B99'
  - '001221A00B26'
